spring:
  ai:
    mcp:
      client:
        enabled: true
        name: chatbot-client
        version: 1.0.0
        type: SYNC
        initialized: true
        request-timeout: 30s
        streamable-http:
          connections:
            server-mcp:
              url: http://127.0.0.1:8389
            server-mcp-mail:
              url: http://127.0.0.1:8381
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
  application:
    name: ChatbotService

logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG
    org.springframework.ai.chat: DEBUG

server:
  port: 8345